module.exports = {
  docs: {
    Introduction: [
      'welcome',
      'using-dbrowser',
    ],
    Developers: [
      'developers/cloning-ddrives',
      'developers/changing-a-ddrive-title-or-thumbnail',
      'developers/comparing-and-merging-ddrives',
      'developers/creating-files-and-folders',
      'developers/importing-and-exporting-files',
      'developers/sharing-ddrives',
      'developers/hosting-ddrives',
      'developers/your-system-ddrive',
      'developers/syncing-with-folders',
      'developers/using-the-terminal',
      'developers/using-the-editor',
      'developers/creating-mounts',
      'developers/editing-file-metadata',
      'developers/creating-new-ddrives',
      'developers/comparing-and-merging-ddrives',
    ],
    Resources: [
      'resources/what-is-a-ddrive',
      'resources/index.json-manifest',
      'resources/content-type-negotiation',
      'resources/frontends-.ui-folder',
      'resources/goto-files',
      'resources/hole-punchability',
    ],
    APIs: [
      'apis/dbrowser.capabilities',
      'apis/dbrowser.contacts',
      'apis/dbrowser.ddrive',
      'apis/dbrowser.markdown',
      'apis/dbrowser.panes',
      'apis/dbrowser.peersockets',
      'apis/dbrowser.shell',
      'apis.dbrowser.terminal',
    ],    
  },
};